import Footer from "@/components/layout/Footer";
import "./globals.css";
import SubFooter from "@/components/layout/SubFooter";
import Header from "@/components/layout/Header";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "@/components/shared/ReduxProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ReduxProvider>
        <html lang="en">
          <body className="">
            {" "}
            <Header />
            {children}
            <Footer />
            <SubFooter />
          </body>
        </html>
      </ReduxProvider>
    </ClerkProvider>
  );
}
