import Footer from "@/components/layout/Footer";
import "./globals.css";
import SubFooter from "@/components/layout/SubFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        {" "}
        {children}
        <Footer />
        <SubFooter />
      </body>
    </html>
  );
}
